######################################
# Script defines project pipeline via series of actions
######################################

version: '3.0'

expectations:
  population_size: 10000

actions:

  # Extract data ----
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv
  
